Entity 세팅
TeamFILL-IN/server-renew pull request #11
Opened 2023-11-18 15:26 UTC by oownahcohc

- #7

2023-11-18 15:40 UTC, oownahcohc reviewed
확실하지 않은 부분에 코멘트 남겨뒀어요! 🙂

2023-11-18 15:40 UTC, oownahcohc commented on fillin/src/main/java/com/teamfillin/fillin/domain/photo/Status.java
>  }
저희 photo 에서 status 가 뭐를 의미했죠,,!?😂

2023-11-18 15:40 UTC, oownahcohc commented on fillin/src/main/java/com/teamfillin/fillin/domain/price/Price.java
> +
H2 에서는 value 라는 필드명이 허용이 안되나봐요! 임시적으로 price 로 변경했습니다

2023-11-18 15:40 UTC, oownahcohc commented on fillin/src/main/java/com/teamfillin/fillin/domain/account/SocialInfo.java
> +}
일단 그냥 java 7+ 에서 기본적으로 제공되는 equals&hashCode 사용했어요!

2023-11-18 15:40 UTC, oownahcohc commented on fillin/src/main/java/com/teamfillin/fillin/domain/photo/Photo.java
> +@EntityListeners(AuditingEntityListener.class)
`@EnableJpaAuditing` 을 아직 적용을 안해줬는데, 전체적인 config 관리는 어떻게 하는게 좋을까요?

2023-11-18 15:40 UTC, oownahcohc commented on fillin/src/main/java/com/teamfillin/fillin/domain/photo/Photo.java
> +	private String imagePath;
일단 저희 저번에 #5 에서 만든 테이블로 가져갔는데, `image_domain`, `image_path` 로 가져가기로 했던것 같아서 
이 부분 혹시 바꿔야 할까요~?

2023-11-18 15:40 UTC, oownahcohc commented on fillin/src/main/java/com/teamfillin/fillin/domain/reactionHistory/TargetType.java
> +}
TargetType 도 확실히 기억이 안나서..! 
사진에 대한 리액션인지, 매장에 대한 북마크인지 구분하는 값이었던 것 같은데,,,🤔

2023-11-19 05:41 UTC, daehwan2da requested changes
- 전체적으로 기본 생성자를 protected 로 제한하셨는데 이유가 있으실까요? (private 으로 하는건 어떠실까요~?)
- BaseEntity 만들어서 AuditingEntityListener 상속하면 좋을것같습니다 😄

2023-11-19 05:41 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/account/SocialInfo.java
> +	@Column(nullable = false, length = 100, unique = true)
unique 가 각 컬럼 별로 적용되어있네요. (이렇게되면 unique(socialId), unique(socialType) 이런식으로 적용되어집니다!
- 저희 설계상은 unique(socialType, socialId) 로 적용되어야합니다

2023-11-19 05:41 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/account/SocialInfo.java
> +	@Column(nullable = false, length = 100, unique = true)
```suggestion
	@Column(nullable = false, length = 100)
```

2023-11-19 05:41 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/account/SocialInfo.java
> +	@Column(nullable = false, length = 10, unique = true)
```suggestion
	@Column(nullable = false, length = 10)
```

2023-11-19 05:41 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/account/SocialInfo.java
> +	protected SocialInfo() {
protected 로 제한하신 이유가 있으실까용?

2023-11-19 05:41 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/account/Account.java
> +@Entity
Table 명 명시하면 좋을것같아요!
추가로, 복합 unique key 도 해당 영역에서 설정가능합니다.

```suggestion
@Entity
@Table(
	name = "account",
	indexes = {
		@Index(name = "idx_unique_01", columnList = "socialType, socialId")
	}
)
```

<img width="801" alt="스크린샷 2023-11-19 오후 2 05 30" src="https://github.com/TeamFILL-IN/server-renew/assets/88091704/b343281a-ccfb-47e6-a413-07715b34fbcc">



- 원래 기존에 unique Key 에 user_no 도 넣었는데, 제거해도 될것같습니다!

2023-11-19 05:41 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/account/Account.java
> +	@Column(nullable = false, unique = true)
```suggestion
	@Column(nullable = false)
```

- userNo 에 단독 unique 가 걸려있으면, N:M 구성이 어렵습니다
  - user 1개에 N 개의 SocialAccount 매핑이 될 수 없음

2023-11-19 05:41 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/user/Status.java
> +public enum Status {
UserStatus 로 네이밍이 명확하면 좋을것같습니다~
```suggestion
public enum UserStatus {
```

Status 라는 네이밍을 사용한다면, public 을 제거해 user package 안에서만 접근가능하게 해야할것같아요~

```suggestion
enum Status {
```

2023-11-19 05:41 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/studio/Studio.java
> +public class Studio {
status 필드가 누락되었습니다

2023-11-19 05:41 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/studio/Studio.java
> +	public Studio(String name, String address, String tel, Double latitude, Double longitude, String etc, String site) {
Builder 패턴 적용해두는건 어떠실까요?

2023-11-19 05:41 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/price/Price.java
> +
ㅎㅎ amount 로 db 설계 네이밍 변경하시죠

2023-11-19 05:41 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/runningTime/Day.java
해당 클래스 네이밍도 `DayOfWeek` 어떠실까요~?

2023-11-19 05:41 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/runningTime/RunningTime.java
> +	private Day dayOfWeek;
dayOfWeek 네이밍 좋네요!
db 설계에 day_of_week 로 네이밍 변경 반영해두었습니다~

2023-11-19 05:41 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/photo/Photo.java
> +@EntityListeners(AuditingEntityListener.class)
넵 BaseEntity 구성해두면 좋을것같습니다

2023-11-19 05:41 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/photo/Photo.java
> +	private String imagePath;
아뇨! path 만 두시면됩니다.
domain 을 yaml에서 세팅한 값을 주입시켜줄거에요~

2023-11-19 05:41 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/photo/Status.java
UserStatus 와 같은 의견입니다

2023-11-19 05:41 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/reactionHistory/ReactionHistory.java
Account 와 같이 복합 unique 적용부탁드리겠습니다~

2023-11-19 05:41 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/reactionHistory/TargetType.java
> +}
PHOTO, STUDIO 로 구성하면 될것같습니다!

2023-11-19 06:41 UTC, oownahcohc commented on fillin/src/main/java/com/teamfillin/fillin/domain/photo/Photo.java
> +	private String imagePath;
아하 그런 방식으로 하는군요! 넵 ㅎㅎ

2023-11-19 06:51 UTC, oownahcohc commented
> * 전체적으로 기본 생성자를 protected 로 제한하셨는데 이유가 있으실까요? (private 으로 하는건 어떠실까요~?)

`@Entity` 로 매핑된 객체 조회를 할때 리플랙션을 이용하기 때문에 private 으로 기본 생성자를 만들면 접근을 못하는 걸로 알고있었거든요!!
혹시 제가 잘못 알고 있는 걸까요?!

> * BaseEntity 만들어서 AuditingEntityListener 상속하면 좋을것같습니다 😄

모든 엔티티에 사용될 것 같지 않아서 별개로 적용했는데, BaseEntity 로 만들어서 상속하는게 관리가 더 편할까요?!

2023-11-19 06:53 UTC, oownahcohc commented on fillin/src/main/java/com/teamfillin/fillin/domain/account/SocialInfo.java
> +	@Column(nullable = false, length = 100, unique = true)
> * 저희 설계상은 unique(socialType, socialId) 로 적용되어야합니다

적용하면서 이상했는데 역시 잘못됐었군요 😅

2023-11-19 06:56 UTC, oownahcohc commented on fillin/src/main/java/com/teamfillin/fillin/domain/account/Account.java
> +@Entity
오.. 이런식으로 하는게 가능하군요!! 

> indexes = {
> 		@Index(name = "idx_unique_01", columnList = "socialType, socialId")
> 	}

이 부분이 복합 unique key 를 설정하는 코드인가요?

2023-11-19 06:56 UTC, oownahcohc commented on fillin/src/main/java/com/teamfillin/fillin/domain/user/Status.java
> +public enum Status {
UserStatus 로 가져가겠습니다!!

2023-11-19 06:59 UTC, oownahcohc commented on fillin/src/main/java/com/teamfillin/fillin/domain/studio/Studio.java
> +	public Studio(String name, String address, String tel, Double latitude, Double longitude, String etc, String site) {
넵 좋습니다! ㅎㅎ 제가 Builder 를 잘 사용하지 않다 보니,,😅

2023-11-19 07:13 UTC, daehwan2da commented
> @Entity 로 매핑된 객체 조회를 할때 리플랙션을 이용하기 때문에 private 으로 기본 생성자를 만들면 접근을 못하는 걸로 알고있었거든요!!
혹시 제가 잘못 알고 있는 걸까요?!

오.. 맞네요..! 확인 감사합니다 :) 

> 모든 엔티티에 사용될 것 같지 않아서 별개로 적용했는데, BaseEntity 로 만들어서 상속하는게 관리가 더 편할까요?!

음 일괄적으로 적용할 수 있을것같아서요, createdAt,  updatedAt 이 적용되어지는 엔티티들에 대해서는 모두 적용하면 좋을것같습니다~!

2023-11-19 08:12 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/account/Account.java
> +@Entity
정확히는 unique index 는 db 에서 설정하는건데요, (위처럼 안하고, db 구성시 직접 쿼리로 세팅)
위처럼 해두면 명시적으로 index 가 어떻게 구성되어있는지 알기 쉽고,
jpa auto ddl 에 적용됩니다

2023-11-19 08:17 UTC, daehwan2da approved these changes

2023-11-19 08:17 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/photo/Photo.java
> +@EntityListeners(AuditingEntityListener.class)
아 질문에 답변이 이상했군요 ㅋㅋ FillinApplication 에 말씀주신 어노테이션 적용하면 될것같습니다

2023-11-19 08:18 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/reactionHistory/ReactionHistory.java
> +		@Index(name = "idx_unique_02", columnList = "userNo, targetNo, targetType")
02 로 하신 이유가 있으실까요??

2023-11-19 08:19 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/studio/Studio.java
> +	public Studio(String name, String address, String tel, Double latitude, Double longitude, String etc, String site) {
lombok builder 열어두어서 그냥 `@Builder` 명시해주시면 될 것 같습니다

2023-11-19 08:27 UTC, oownahcohc commented on fillin/src/main/java/com/teamfillin/fillin/domain/reactionHistory/ReactionHistory.java
> +		@Index(name = "idx_unique_02", columnList = "userNo, targetNo, targetType")
아 `idx_unique_01` 로 설정했었는데 JDBC 에서 DDL 실행 시에 이미 있는 이름이라고 예외를 던지더라구요!
혹시 index 네이밍 관련해서 뭔가 규칙이 있을까요?! 한번도 안써봐서 ㅎㅎ

2023-11-20 00:57 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/reactionHistory/ReactionHistory.java
> +		@Index(name = "idx_unique_02", columnList = "userNo, targetNo, targetType")
음.. ㅋㅋ 머 저 네이밍은 중요한건 아니라서 ㅎㅎ 02 로 가시죠!

2023-11-20 04:26 UTC, merged