studio 조회 관련 기능 개발
TeamFILL-IN/server-renew pull request #28
Opened 2023-12-02 18:15 UTC by oownahcohc

### 관련 이슈
- #25 
- #22 : 해당 이슈 관련해서 질문 드릴게 있어서 언급했습니다. 저는 도메인을 pure 하게 가져가기 위해서는 도메인 엔티티가 영속성 엔티티를 몰라야 한다고 생각해서, StudioEntity 내부에 toStudio 메서드를 두어 매핑해주는 형태로 가져갔는데요, 어떻게 생각하시나요?!
### studio 전체 조회
현재 studio 데이터가 적기 때문에, 전체 조회 시 모든 스튜디오를 내려주는 것으로 개발 진행했습니다.

### studio 상세 조회
- 기존 studio 의 time, price 컬럼 타입이 `TEXT` 였기 때문에, 해당 부분 api response 가 매우 자유분방합니다. api response 관련해서 클라이언트와 논의가 필요할 듯 합니다. [ [현상소 데이터](https://github.com/TeamFILL-IN/server-renew/files/13536999/default.xlsx) ]
- 최대한 맞추고자 `RunnigTimeEntity` 에  `OperationStatus`, `DayOfWeek` 에 `EVERY_DAY`, `WEEK_DAY`, `WEEK_END` 등 추가했습니다.
- time, price 의 response 형식은 도메인 로직과는 별개로 `사용자 인터페이스와 데이터 표현 관련 로직(뷰 로직)`으로 판단해서, 각각  `뷰 모델`로 분리했습니다.

### studio 검색
studio 검색 관련해서는 글 작성한게 살짝 있는데 다듬어지는대로 #27 이슈에 공유하도록 할게요!! 
- `InputKeyword` : 사용자가 입력한 검색어에 대한 객체입니다. 공백 기준으로 입력 검색어를 split 합니다
- `KeywordManager` : 공백 기준으로 나뉜 inputKeyword 의 토근에 대해서 각각 등급을 설정하는데요, 저희 서비스는 어차피 현상소, 스튜디오 검색이기 때문에 `~ 현상소`, `~ 스튜디오` 식으로 들어오는 검색어에서 `현상소`, `스튜디오` 는 검색어 키워드로서의 가치가 낮다고 판단했습니다. 따라서 이와 관련된 단어들을 StopWord 로 설정해놓고 이외의 token들의 가치를 더 높게 설정해서 비즈니스 검색어를 만들어주도록 짰습니다.

2024-01-07 07:39 UTC, daehwan2da requested changes
1) 레이어간 dto naming 이 모호한데요, 간단히 컨벤션 정의해 프로젝트 전반에 적용되면 좋을것같습니다
(Api) <- ~Result (View or Result 의견 주세요~)_ -> (Service) <- domain model -> (Service Component)

2) 전반적으로 레이어 dto 간 의존이 혼동되고있는데요, top-down 으로 통일되면 좋을것같습니다
- Api package 의 class 들은 Service Layer 에서 import 되지 않도록
    - ServiceLayer 에서 Response 를만들어 Api 로 전달하는것이 아닌,  전달될 dto 를 만들어 응답, Api 에서 dto 를 받아서 Response 구성

3) base/20231126 부시 새롭게 해두겠습니다. 리베이스 한번 하시고 푸시 부탁드릴게요

2024-01-07 07:39 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/studio/StudioRetriever.java
> +		return studioRepository.findAll()
주석으로 full scan 한다고 주의 달아두면 좋을것같습니다

2024-01-07 07:39 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/studio/Studio.java
> +	private Studio(long no, String name, String address, String tel, StudioLocation location, String etc,
생성할때 미리 StudioLocation 에 대한 null assert 가 있으면 좋을것같습니다 (field validation)
- getter 에서 바로 get 하는데, null 이 아니라는 보장을 하기 위함입니다.

2024-01-07 07:39 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/api/studio/StudioRetrieveAllResponse.java
> +	private final List<StudioLocationResult> studios;
StudioLocationResult 를 api 에서 바로 리턴하는것 보다는, Response 를 추가로 만들어 핸들링하는게 좋을것같습니다.
- 이유 : 내부 dto 변경이 client 에게 제공되는 interface 에 영향을 주지 않도록 분리
  - StudioLocationResult 를 바로 응답하면, 로직내에서 필드가 변경되었을때 클라이언트 응답에도 영향을 주게됨

2024-01-07 07:39 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/api/studio/StudioRetrieveApi.java
> +	public FillinApiResponse retrieveStudioDetail(@PathVariable long studioId) {
studioNo 로 네이밍 정의하는건 어떠실까요?

2024-01-07 07:39 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/studio/TimeConfiguration.java
> +	@Bean
해당 Bean 은 Application 클래스 에서 설정되어도 좋을것같습니다 (전역에서 공통으로 사용되도록)

2024-01-07 07:39 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/studio/view/StudioView.java
> +public class StudioView {
StudioView 하고, Studio class 하고 차이가 무엇일까요? Studio 하나로 통일하면 좋을것같다고 생각듭니다

2024-01-07 07:39 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/studio/StudioDetailRetrieveService.java
> +	public StudioDetailResponse retrieveDetail(long studioNo) {
도메인 레이어에서는 api 클래스를 몰라야할것같습니다.
StudioDetail 관련 클래스를 응답주고, api level 에서 Response 로 파싱해주는 작업이 수행되어야할것같습니다.

2024-01-07 07:39 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/studio/StudioDetailRetrieveService.java
> +	public StudioDetailResponse retrieveDetail(long studioNo) {
여기서는 다 ~View 같은 dto 로 파싱되어 핸들링되기보다, Studio, Price, RunningTime 같은 각 도메인의 모델들이 응답되고, 이 응답들을 어그리게이션 하는 dto 클래스 모델로 리턴하면 좋을것같습니다 (ex. SudtioDetailView)

- Service Layer 의 클래스들을 하위 Layer 에서는 의존되지 않도록 하기위함
  - ~View class 들이 하위 Layer 에서 의존되게됨

2024-01-07 07:39 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/studio/StudioExceptionHandler.java
> +	public static FillinException notFount() {
오타있습니다 `fount` -> `found`

2024-01-07 07:39 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/studio/InputKeyword.java
> +	public static InputKeyword from(String keyword) {
keyword 가 null 로 들어올 경우, emptyList 로 채워주어야할것같습니다. (NPE 방어로직 구현 필요)

2024-01-07 07:39 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/studio/KeywordManager.java
> +		static List<String> replaceStopWordToModifiedWord(List<String> keywordTokens) {
unit test 작성 부탁드리겠습니다~

2024-01-07 07:39 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/studio/KeywordManager.java
> +		static void removeStopWordIn(List<String> keywordTokens) {
unit test 작성 부탁드리겠습니다~

2024-01-07 07:39 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/studio/KeywordManager.java
> +class KeywordManager {
해당 클래스에 대해서 test case 정리해서 test 작성되면 좋을것같습니다

2024-01-07 07:39 UTC, daehwan2da commented on fillin/src/main/java/com/teamfillin/fillin/domain/runningTime/view/RunningTimeInfoFormatter.java
> +abstract class RunningTimeInfoFormatter {
구현체들에 대해서 unit test 있으면 좋을것같습니다

2024-01-07 09:38 UTC, daehwan2da commented
https://github.com/TeamFILL-IN/server-renew/pull/33/files
해당 PR 참고해 api response 를 ResponseEntity 로 변경 부탁드립니다! 
(status code 를 담기 위해 변경했었습니다.)

2024-01-08 16:12 UTC, oownahcohc commented on fillin/src/main/java/com/teamfillin/fillin/api/studio/StudioRetrieveApi.java
> +	public FillinApiResponse retrieveStudioDetail(@PathVariable long studioId) {
좋습니다 ㅎㅎ
기존 api 문서에 나온대로 만들었던 것 같은데, 통일성 있게 studioNo 로 가는게 좋을 것 같네요!!

2024-01-08 16:13 UTC, oownahcohc commented on fillin/src/main/java/com/teamfillin/fillin/domain/studio/TimeConfiguration.java
> +	@Bean
넵 설정해놓겠습니다!

2024-01-08 16:28 UTC, oownahcohc commented on fillin/src/main/java/com/teamfillin/fillin/domain/studio/TimeConfiguration.java
> +	@Bean
전역에서 사용되는 설정 사항들을 보통 Application 클래스에서 관리하는 방식으로 가져가시나요!?
저는 지금까지 보통 config 클래스를 만들어서 관리했었는데, 궁금해서 여쭤봐요!! ㅎㅎ

2024-01-08 16:32 UTC, oownahcohc commented on fillin/src/main/java/com/teamfillin/fillin/domain/studio/view/StudioView.java
> +public class StudioView {
위에 말씀드렸던 것 처럼 클라이언트 응답에 종속적인, 도메인 로직과는 좀 별개의 역할을 한다고 생각해서 분리 했었는데요.
지금 보니깐 리뷰 주신 것 처럼 굳이 분리할 필요 없을 것 같은 로직들이긴 하네요!!

2024-01-08 17:58 UTC, oownahcohc commented
> https://github.com/TeamFILL-IN/server-renew/pull/33/files
> 해당 PR 참고해 api response 를 ResponseEntity 로 변경 부탁드립니다!

넵 확인했습니다!!

2024-01-08 17:59 UTC, oownahcohc commented on fillin/src/main/java/com/teamfillin/fillin/domain/studio/StudioExceptionHandler.java
> +	public static FillinException notFount() {
오 감사합니다!!

2024-01-08 18:34 UTC, oownahcohc commented on fillin/src/main/java/com/teamfillin/fillin/domain/studio/StudioDetailRetrieveService.java
> +	public StudioDetailResponse retrieveDetail(long studioNo) {
> time, price 의 response 형식은 도메인 로직과는 별개로 사용자 인터페이스와 데이터 표현 관련 로직(뷰 로직)으로 판단해서, 각각 뷰 모델로 분리했습니다.

여기서 ~View 형식으로 핸들링 한건, 위에 말씀드린 것 처럼 api 응답 형식에 의존적인 로직이라고 생각해서였습니다. 그래서 View 와 관련된 도메인들을 일급 컬렉션으로 관리해 데이터 표현 관련 비즈니스 로직을 한곳에서 관리해주도록 한 것인데요. 
때문에 이 ~View 객체들을 저는 그냥 도메인 모델들을 관리하는 또 다른 도메인 모델이라고 생각합니다.



> Service Layer 의 클래스들을 하위 Layer 에서는 의존되지 않도록 하기위함
> * ~View class 들이 하위 Layer 에서 의존되게됨

그래서 이 부분이 지금 제가 잘 이해가 가지 않는 것 같아요. 새벽이라 머리가 안돌아가서 그런지,,,ㅋㅋㅋ
~View 클래스들이 하위 레이어인 repository 계층에서 의존된다는 말씀이신가요?!

2024-01-15 02:31 UTC, daehwan2da approved these changes

2024-01-15 17:31 UTC, merged